In [3]:
import numpy as np

# Latihan 2D Array

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A, "\n")
#Lengkapi kodingan berikut
print('banyaknya entry = ', A.size)
print('dimensi array = ', A.ndim)
print('ukuran array = ', A.shape, "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3) 



# Latihan Slicing

In [5]:
#Lengkapi kodingan berikut
print('baris ke-3 = \n', A[2])
print('entry ke-1 & 2 baris ke-3 = ', A[2][0:2])
print('entry ke-2 & 3 kolom ke-3 = \n', A[1:3,2:]) #Baris 1-2 kolom >= 2

baris ke-3 = 
 [7 8 9]
entry ke-1 & 2 baris ke-3 =  [7 8]
entry ke-2 & 3 kolom ke-3 = 
 [[6]
 [9]]


# Operasi Matriks

## Hitunglah:
    *   2*A
    *   2+A
    *   A+B
    *   A-B
    *   determinan A
    *   invers dari B, simpan jadi matriks D
    *   transpose D
    *   nilai eigen dan vektor eigen dari A dan B

In [15]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

print(A)
print(B)

[[1 2]
 [7 8]]
[[3 5]
 [1 6]]


In [16]:
2*A

array([[ 2,  4],
       [14, 16]])

In [17]:
2+A

array([[ 3,  4],
       [ 9, 10]])

In [18]:
A+B

array([[ 4,  7],
       [ 8, 14]])

In [19]:
A-B

array([[-2, -3],
       [ 6,  2]])

In [20]:
print(np.linalg.det(A))

-6.0


In [22]:
D = (np.linalg.inv(B))
print(D)

[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]


In [23]:
print(np.transpose(D))

[[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]


In [29]:
print("Nilai Eigen A = ", np.linalg.eig(A)[0])
print("Vector Eigen A = \n", np.linalg.eig(A)[1])
print("")
print("Nilai Eigen B = ", np.linalg.eig(B)[0])
print("Vector Eigen B = \n", np.linalg.eig(B)[1])

Nilai Eigen A =  [-0.62347538  9.62347538]
Vector Eigen A = 
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]

Nilai Eigen B =  [1.8074176 7.1925824]
Vector Eigen B = 
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


### *Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)? *

In [31]:
print(B * D)

[[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]


In [32]:
print(np.matmul(B,D))

[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]
